"""Initial migration - sorting area tables

Revision ID: 1648cf2d4935
Revises: 
Create Date: 2026-02-12 00:20:12.570225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1648cf2d4935'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dzialy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opis_kategorii', sa.String(length=100), nullable=True),
    sa.Column('koszt_pracy', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opis_kategorii')
    )
    op.create_table('operatorzy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nr_operatora', sa.Integer(), nullable=True),
    sa.Column('imie_nazwisko', sa.String(length=100), nullable=True),
    sa.Column('dzial_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dzial_id'], ['dzialy.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nr_operatora')
    )
    op.create_table('dane_z_raportow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nr_raportu', sa.String(length=50), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('nr_niezgodnosci', sa.String(length=50), nullable=True),
    sa.Column('data_niezgodnosci', sa.Date(), nullable=True),
    sa.Column('nr_zamowienia', sa.String(length=50), nullable=True),
    sa.Column('kod_detalu', sa.String(length=50), nullable=True),
    sa.Column('nr_instrukcji', sa.String(length=50), nullable=True),
    sa.Column('selekcja_na_biezaco', sa.Boolean(), nullable=True),
    sa.Column('ilosc_detali_sprawdzonych', sa.Integer(), nullable=True),
    sa.Column('zalecana_wydajnosc', sa.Float(), nullable=True),
    sa.Column('czas_pracy', sa.Float(), nullable=True),
    sa.Column('uwagi', sa.Text(), nullable=True),
    sa.Column('uwagi_do_wydajnosci', sa.Text(), nullable=True),
    sa.Column('data_selekcji', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operatorzy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('braki_defekty_raportow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raport_id', sa.Integer(), nullable=True),
    sa.Column('defekt', sa.String(length=200), nullable=True),
    sa.Column('ilosc', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['raport_id'], ['dane_z_raportow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('braki_defekty_raportow')
    op.drop_table('dane_z_raportow')
    op.drop_table('operatorzy')
    op.drop_table('dzialy')
    # ### end Alembic commands ###
