"""Add opis_niezgodnosci to DaneRaportu

Revision ID: fbbfe52bc671
Revises: 1648cf2d4935
Create Date: 2026-02-23 14:51:22.469117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbbfe52bc671'
down_revision = '1648cf2d4935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dane_z_raportow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opis_niezgodnosci', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dane_z_raportow', schema=None) as batch_op:
        batch_op.drop_column('opis_niezgodnosci')

    # ### end Alembic commands ###
